routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RestTestController;
use App\Http\Controllers\Blog\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('blog/posts', PostController::class);
Route::resource('/trello/desk_web' , App\Http\Controllers\Trello\DeskController::class);
Route::resource('/trello/list_web' , App\Http\Controllers\Trello\ListController::class);

Route::resource('test', RestTestController::class);
Route::resource('/blog/admin/categories', \App\Http\Controllers\Blog\Admin\CategoryController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pagination = DB::table('blog_categories')->paginate(5);
        return view('blog.admin.categories.index', [
            'paginator' => $pagination
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new BlogCategory();
        return view('blog.admin.categories.create',[
            'item'=>$item
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();
        if(empty($data['slug'])){
            $data['slug'] = \Str::slug($data['title']);
        }
         $item = new BlogCategory([
             'title'=>$data['title'],
             'slug'=>$data['slug']
         ]);
        $item->save();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = DB::table('blog_categories')->find($id);
        return view('blog.admin.categories.edit', [
            'item' => $item]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
        $item = DB::table('blog_categories')->find($id);

        if (empty($item)) {
            return back(301)
                ->withErrors(['msg' => "Запись id=[{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();

        $result =   DB::table('blog_categories')->where('id',$id)->update(['title'=>$data['title']]);

        if ($result) {
            return redirect()
                ->route('categories.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/blog/admin/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <form method="POST" action="{{route('categories.store')}}">
        @include('blog.admin.categories.include.main')
    </form>

@endsection

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <form method="POST" action="{{route('categories.update',$item->id)}}">
        @method('PUT')
        @include('blog.admin.categories.include.main')
    </form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{ route('categories.create') }}">Добавить</a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">

                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Категория</th>
                                <th>Родитель</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($paginator as $item)
                                @php /** @var \App\Models\BlogCategory $item */ @endphp
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>
                                        {{--<a href="{{ route('blog/admin/categories/'.$item->id.'/edit')  }}">--}}
                                        <a href="{{ route('categories.edit',$item->id)  }}">
                                            {{ $item->title }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ $item->parent_id }}{{-- $item->parentCategory->title --}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {!! $paginator->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection