routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RestTestController;
use App\Http\Controllers\Blog\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('blog/posts', PostController::class);
Route::resource('/trello/desk_web' , App\Http\Controllers\Trello\DeskController::class);
Route::resource('/trello/list_web' , App\Http\Controllers\Trello\ListController::class);

Route::resource('test', RestTestController::class);
Route::resource('/blog/admin/categories', \App\Http\Controllers\Blog\Admin\CategoryController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Trello/Card.php
<?php

namespace App\Models\Trello;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Card extends Model
{
    use HasFactory;
    protected $fillable = ['name','list_id'];
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Models/Trello/Desk.php
<?php

namespace App\Models\Trello;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Desk extends Model
{
    use HasFactory;

    protected $fillable = ['name','description'];
    public function lists()
    {
        return $this->hasMany(List_::class);
    }





}

app/Models/Trello/List_.php
<?php

namespace App\Models\Trello;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class List_ extends Model
{
    use HasFactory;

    protected $table = 'lists';
    protected $fillable = ['name','desk_id'];
    public function cards()
    {
        return $this->hasMany(Card::class,'list_id');
    }

}

app/Models/Trello/Task.php
<?php

namespace App\Models\Trello;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $fillable = ['name','cards_id'];
}

app/Http/Controllers/Api/V1/Trello/CardController.php
<?php

namespace App\Http\Controllers\Api\V1\Trello;

use App\Http\Controllers\Controller;
use App\Http\Resources\Trello\CardResource;
use App\Models\Trello\Card;
use Illuminate\Http\Request;

class CardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return CardResource::collection(Card::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Card $card)
    {
        return  new CardResource($card);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Card $card)
    {
         $card->delete();
        return response()->json([
            'status' => 'OK',
            'message' => 'Card deleted. id:'.$card->id
        ]);
    }
}

app/Http/Controllers/Api/V1/Trello/DeskController.php
<?php

namespace App\Http\Controllers\Api\V1\Trello;

use App\Http\Controllers\Controller;
use App\Http\Requests\Trello\DeskStoreRequest;
use App\Http\Resources\Trello\DeskResource;
use App\Models\Trello\Desk;
use Illuminate\Http\Request;

class DeskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // return Desk::all();
       return DeskResource::collection(Desk::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return DeskResource
     */
    public function store(DeskStoreRequest $request)
    {
        $createdDesk = Desk::create($request->validated());
        return  new DeskResource($createdDesk);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Desk $desk)
    {
      // return  Desk::find($id);
       return  new DeskResource($desk);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DeskStoreRequest $request, Desk $desk)
    {
        $desk->update($request->validated());
        return  new DeskResource($desk);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Desk $desk)
    {
        $desk->delete();
        return response()->json([
            'status' => 'OK',
            'message' => 'Desc deleted. id:'.$desk->id,
        ]);
    }
}

app/Http/Controllers/Api/V1/Trello/List_Controller.php
<?php

namespace App\Http\Controllers\Api\V1\Trello;

use App\Http\Controllers\Controller;
use App\Http\Resources\Trello\List_Resource;
use App\Models\Trello\List_;
use Illuminate\Http\Request;

class List_Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return List_Resource::collection(List_::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(List_ $list)
    {
        return  new List_Resource($list);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(List_ $list)
    {
        $list->delete();
        return response()->json([
            'status' => 'OK',
            'message' => 'List deleted. id:'.$list->id
        ]);
    }
}

app/Http/Controllers/Api/V1/Trello/TaskController.php
<?php

namespace App\Http\Controllers\Api\V1\Trello;

use App\Http\Controllers\Controller;
use App\Http\Resources\Trello\TaskResource;
use App\Models\Trello\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return TaskResource::collection(Task::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        return  new TaskResource($task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Task $task)
    {
        $task->delete();
        return response()->json([
            'status' => 'OK',
            'message' => 'Task deleted. id:'.$task->id
        ]);
    }
}

app/Http/Controllers/Api/V2/Trello/DeskController.php
<?php

namespace App\Http\Controllers\Api\V2\Trello;

use App\Http\Controllers\Controller;
use App\Http\Requests\Trello\DeskStoreRequest;
use App\Http\Resources\Trello\DeskResource;
use App\Models\Trello\Desk;
use Illuminate\Http\Request;

class DeskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Desk::all();
       //return DeskResource::collection(Desk::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return DeskResource
     */
    public function store(DeskStoreRequest $request)
    {
        $createdDesk = Desk::create($request->validated());
        return  new DeskResource($createdDesk);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Desk $desk)
    {
      // return  Desk::find($id);
       return  new DeskResource($desk);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DeskStoreRequest $request, Desk $desk)
    {
        $desk->update($request->validated());
        return  new DeskResource($desk);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Desk $desk)
    {
        $desk->delete();
        return response(null,204);
    }
}

app/Http/Controllers/Trello/DeskController.php
<?php

namespace App\Http\Controllers\Trello;

use App\Http\Controllers\Controller;
use App\Http\Requests\Trello\DeskStoreRequest;
use App\Models\Trello\Desk;
use App\Models\Trello\List_;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
class DeskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $desks = Desk::paginate(5,['id','name','description']);
        return view('trello.desks.index',['desks'=>$desks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $desk = new Desk();
        return view('trello.desks.create',['item'=>$desk]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DeskStoreRequest $request)
    {
        Desk::create($request->validated());
        return redirect()->route('desk_web.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Trello\Desk  $desk
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $desk = Desk::with('lists')->findOrFail($id);
        return view('trello.desks.show',['desk'=>$desk]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Trello\Desk  $desk
     * @return \Illuminate\Http\Response
     */
    public function edit( $id,Request $request)
    {
        $desk = Desk::findOrFail($id);
        return view('trello.desks.edit',['desk'=>$desk]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Trello\Desk  $desk
     * @return \Illuminate\Http\Response
     */
    public function update(DeskStoreRequest $request, $id)
    {
        Desk::findOrFail($id)->update($request->validated());
        return redirect()->route('desk_web.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Trello\Desk  $desk
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Desk::destroy($id);
        return redirect()->route('desk_web.index');
    }
}

app/Http/Controllers/Trello/ListController.php
<?php

namespace App\Http\Controllers\Trello;

use App\Http\Controllers\Controller;
use App\Http\Requests\Trello\ListStoreRequest;
use App\Models\Trello\List_;
use Illuminate\Http\Request;

class ListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $list = List_::with('cards')->findOrFail($id);
        return view('trello.lists.show',['list'=>$list]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $list = List_::findOrFail($id);
        return view('trello.lists.edit',['list'=>$list]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ListStoreRequest $request, $id)
    {
         $desc_id = $request->validated()['desk_id'];
         List_::findOrFail($id)->update($request->validated());

        return redirect( route('desk_web.show',$desc_id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        List_::destroy($id);
        return back(301);
    }
}

resources/views/trello/desks/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        @if($errors->any())
            <div class="row justify-content-center">
                <div class="col-md-11">
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&#10008;</span>
                        </button>
                        {{$errors->first()}}
                    </div>
                </div>
            </div>
        @endif
        <form action="{{route('desk_web.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <input type="text" name="name" value="{{old('name', $item->name)}}">
            </div>
            <div class="form-group">
                <textarea name="description" id="" cols="30" rows="10">{{old('description', $item->description)}}</textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
        <a class="btn btn-primary" href="{{route('desk_web.index')}}">Back</a>
    </div>
@endsection

resources/views/trello/desks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if($errors->any())
            <div class="row justify-content-center">
                <div class="col-md-11">
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&#10008;</span>
                        </button>
                        {{$errors->first()}}
                    </div>
                </div>
            </div>
        @endif
        <form action="{{route('desk_web.update', $desk->id)}}" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <input type="text" name="name" value="{{old('name', $desk->name)}}">
            </div>
            <div class="form-group">
                <textarea name="description" id="" cols="30" rows="10">{{old('description', $desk->description)}}</textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
        <a class="btn btn-primary" href="{{route('desk_web.index')}}">Back</a>
    </div>
@endsection

resources/views/trello/desks/index.blade.php
@extends('layouts.app')

@section('content')

    <h3><a href="{{route('desk_web.create')}}">Create new desk</a></h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        @foreach($desks as $desk)

            <tr>
                <th scope="row">{{$desk->id}}</th>
                <td><a href="{{ route('desk_web.show',$desk->id)  }}">{{$desk->name}}</a></td>
                <td>{{$desk->description}}</td>
                <td>
                    <a href="{{ route('desk_web.edit',$desk->id)}}">
                        <button class="btn btn-warning" type="submit">Edit</button>
                    </a>
                </td>

                <td>
                    <form method="POST" action="{{route('desk_web.destroy',$desk->id)}}">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
    {!! $desks->links() !!}
@endsection

resources/views/trello/desks/show.blade.php
@extends('layouts.app')

@section('content')
    <h3><a href="{{route('desk_web.create')}}">Create new desk</a></h3>
    <h3><a href="{{route('desk_web.index')}}">Show All Desks</a></h3>


    <h1>Id: {{$desk->id}}</h1>
    <h1>Name: {{$desk->name}}</h1>
    <h1>Description: {{$desk->description}}</h1>

    <h1>Lists</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
        </tr>
        </thead>
        @foreach($desk->lists as $list)
            <tr>
                <th scope="row">{{$list->id}}</th>
                <td><a href="{{ route('list_web.show',$list->id)  }}">{{$list->name}}</a></td>
                <td>
                    <a href="{{ route('list_web.edit',$list->id)}}">
                        <button class="btn btn-warning" type="submit">Edit</button>
                    </a>
                </td>
                <td>
                    <form method="POST" action="{{route('list_web.destroy',$list->id)}}">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection